
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int LKEY = 17;
  public static final int LBRACKET = 19;
  public static final int UMINUS = 29;
  public static final int HIGH = 35;
  public static final int INTEGER = 27;
  public static final int CONTINUE = 5;
  public static final int PRODUCT = 31;
  public static final int LESS = 34;
  public static final int FOR = 7;
  public static final int MINUS = 28;
  public static final int AND = 40;
  public static final int NOT = 21;
  public static final int SEMICOLON = 22;
  public static final int RPAR = 16;
  public static final int OR = 41;
  public static final int BOOL = 2;
  public static final int CLASS = 4;
  public static final int INC = 43;
  public static final int EXTERN = 12;
  public static final int PLUS = 30;
  public static final int ASSIGN = 42;
  public static final int IF = 8;
  public static final int ID = 25;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 38;
  public static final int RBRACKET = 20;
  public static final int TRUE = 23;
  public static final int RKEY = 18;
  public static final int DISTINCT = 39;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int MOD = 33;
  public static final int HIGH_EQ = 37;
  public static final int BREAK = 3;
  public static final int VOID = 10;
  public static final int ELSE = 6;
  public static final int POINT = 13;
  public static final int WHILE = 11;
  public static final int LESS_EQ = 36;
  public static final int FLOAT = 26;
  public static final int LPAR = 15;
  public static final int DEC = 44;
  public static final int FLOAT_LITERAL = 46;
  public static final int FALSE = 24;
  public static final int INTEGER_LITERAL = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "ELSE",
  "FOR",
  "IF",
  "RETURN",
  "VOID",
  "WHILE",
  "EXTERN",
  "POINT",
  "COMA",
  "LPAR",
  "RPAR",
  "LKEY",
  "RKEY",
  "LBRACKET",
  "RBRACKET",
  "NOT",
  "SEMICOLON",
  "TRUE",
  "FALSE",
  "ID",
  "FLOAT",
  "INTEGER",
  "MINUS",
  "UMINUS",
  "PLUS",
  "PRODUCT",
  "DIVIDE",
  "MOD",
  "LESS",
  "HIGH",
  "LESS_EQ",
  "HIGH_EQ",
  "EQUAL",
  "DISTINCT",
  "AND",
  "OR",
  "ASSIGN",
  "INC",
  "DEC",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL"
  };
}

