package compilers;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 31;
  public static final int LKEY = 22;
  public static final int LBRACKET = 24;
  public static final int INTEGER = 11;
  public static final int HIGH = 34;
  public static final int CONTINUE = 5;
  public static final int PRODUCT = 30;
  public static final int LESS = 33;
  public static final int FOR = 9;
  public static final int MINUS = 28;
  public static final int AND = 39;
  public static final int SEMICOLON = 27;
  public static final int RPAR = 21;
  public static final int OR = 40;
  public static final int BOOL = 2;
  public static final int CLASS = 4;
  public static final int INC = 42;
  public static final int EXTERN = 16;
  public static final int PLUS = 29;
  public static final int ASSIGN = 41;
  public static final int IF = 10;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 37;
  public static final int RBRACKET = 25;
  public static final int TRUE = 13;
  public static final int RKEY = 23;
  public static final int DISTINCT = 38;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int MOD = 32;
  public static final int HIGH_EQ = 36;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int ELSE = 6;
  public static final int POINT = 18;
  public static final int WHILE = 15;
  public static final int LESS_EQ = 35;
  public static final int FLOAT = 8;
  public static final int LPAR = 20;
  public static final int DEC = 43;
  public static final int FLOAT_LITERAL = 45;
  public static final int EXCLAMATION_MARK = 26;
  public static final int FALSE = 7;
  public static final int INTEGER_LITERAL = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "ELSE",
  "FALSE",
  "FLOAT",
  "FOR",
  "IF",
  "INTEGER",
  "RETURN",
  "TRUE",
  "VOID",
  "WHILE",
  "EXTERN",
  "ID",
  "POINT",
  "COMA",
  "LPAR",
  "RPAR",
  "LKEY",
  "RKEY",
  "LBRACKET",
  "RBRACKET",
  "EXCLAMATION_MARK",
  "SEMICOLON",
  "MINUS",
  "PLUS",
  "PRODUCT",
  "DIVIDE",
  "MOD",
  "LESS",
  "HIGH",
  "LESS_EQ",
  "HIGH_EQ",
  "EQUAL",
  "DISTINCT",
  "AND",
  "OR",
  "ASSIGN",
  "INC",
  "DEC",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL"
  };
}

